version: '3'

networks:
  backend:
    external: true

volumes:
  # bind mounts (for mongodb) doesn't work when using linux images in a windows host system
  mongo-data:
    driver: local

services:
  mongodb:
    image: mongo:jammy
    environment:
      # mongo will always load the database in the volume first
      # for these to take effect, you need to delete the current volume
      - MONGO_INITDB_ROOT_USERNAME=dasun
      - MONGO_INITDB_ROOT_PASSWORD=Ds20020618
      - MONGO_INITDB_DATABASE=tasks_api
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
    restart: unless-stopped
  api-node:
    image: node-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    init: true
    depends_on:
      - mongodb
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://dasun:Ds20020618@mongodb:27017/tasks_api?authSource=admin
      - JWT_SECRET=KH784HDJBD35HJLHSDJH453BJN
    networks:
      - backend
    ports:
      - 3001:3001
    restart: unless-stopped
